# -*- coding: utf-8 -*-
"""evaluate_segmentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18r8AsY_EakrahYu_8v5ihetW08VcGjgF
"""

import torch
def evaluate_segmentation(model, loader, threshold=0.5):
    model.eval()

    total_tp = 0
    total_fp = 0
    total_fn = 0
    total_tn = 0

    with torch.no_grad():
        for images, masks in loader:
            images = images.to(device)
            masks = masks.float().to(device)

            if masks.ndim == 3:
                masks = masks.unsqueeze(1)

            logits = get_logits(model, images)
            probs = torch.sigmoid(logits)
            preds = (probs > threshold).float()

            tp = ((preds == 1) & (masks == 1)).sum()
            fp = ((preds == 1) & (masks == 0)).sum()
            fn = ((preds == 0) & (masks == 1)).sum()
            tn = ((preds == 0) & (masks == 0)).sum()

            total_tp += tp.item()
            total_fp += fp.item()
            total_fn += fn.item()
            total_tn += tn.item()

    eps = 1e-7

    precision = total_tp / (total_tp + total_fp + eps)
    recall = total_tp / (total_tp + total_fn + eps)
    dice = (2 * total_tp) / (2 * total_tp + total_fp + total_fn + eps)
    iou = total_tp / (total_tp + total_fp + total_fn + eps)
    accuracy = (total_tp + total_tn) / (total_tp + total_fp + total_fn + total_tn + eps)

    return {
        "IoU": iou,
        "Dice": dice,
        "Precision": precision,
        "Recall": recall,
        "Accuracy": accuracy
    }