# -*- coding: utf-8 -*-
"""training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qkelYwpPjShDUJTqYZ-gJrS4X5iV8AR
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

import segmentation_models_pytorch as smp

bce_loss = nn.BCEWithLogitsLoss()
dice_loss = smp.losses.DiceLoss(mode="binary")

def loss_fn(preds, masks):
    return bce_loss(preds, masks) + dice_loss(preds, masks)

def get_logits(model, images):
    output = model(images)
    return output


def train_one_epoch(model, loader, optimizer):
    model.train()
    total_loss = 0

    for images, masks in loader:
        images = images.to(device)
        masks = masks.float().to(device)
        masks = masks.unsqueeze(1)

        preds = get_logits(model, images)
        loss = loss_fn(preds, masks)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    return total_loss / len(loader)


def validate(model, loader):

    model.eval()
    total_loss = 0

    with torch.no_grad():
        for images, masks in loader:
            images = images.to(device)
            masks = masks.float().to(device)
            masks = masks.unsqueeze(1)
            preds = get_logits(model, images)
            loss = loss_fn(preds, masks)
            total_loss += loss.item()

    return total_loss / len(loader)


def train_model(model, train_loader, val_loader, optimizer, save_path, epochs=15):
    best_val_loss = float("inf")

    for epoch in range(epochs):
        train_loss = train_one_epoch(model, train_loader, optimizer)
        val_loss = validate(model, val_loader)

        print(f"Epoch {epoch+1}/{epochs}")
        print(f"Train Loss: {train_loss:.4f}")
        print(f"Val Loss:   {val_loss:.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), save_path)
            print("best - saved")

        print()

    return best_val_loss

